# Generated by Django 6.0.2 on 2026-02-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(choices=[('AGUA', 'Bolis de agua'), ('LECHE', 'Bolis de leche')], default='AGUA', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
