# Generated by Django 6.0.2 on 2026-02-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
