# Generated by Django 6.0.2 on 2026-02-21 06:48

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_pedido_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('AGUA', 'Agua'), ('LECHE', 'Leche')], default='AGUA', max_length=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='token',
            field=models.CharField(blank=True, db_index=True, default='temp', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
